version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=vndevteam_nest_auth
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
