version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=nest_auth
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
    driver: local
